package datalayer;

public class QueryUgyfelLekerdezes {

    private int AKTUALIS_UGYFEL_ID;
    private String AKTUALIS_UGYFEL_MEGSZOLITAS;
    private String AKTUALIS_UGYFEL_KERESZTNEV;
    private String AKTUALIS_UGYFEL_VEZETEKNEV;
    private String AKTUALIS_UGYFEL_EMAIL;
    private String AKTUALIS_UGYFEL_TELEFON;

    public int getAKTUALIS_UGYFEL_ID() {
        return AKTUALIS_UGYFEL_ID;
    }

    public void setAKTUALIS_UGYFEL_ID(int AKTUALIS_UGYFEL_ID) {
        this.AKTUALIS_UGYFEL_ID = AKTUALIS_UGYFEL_ID;
    }

    public String getAKTUALIS_UGYFEL_MEGSZOLITAS() {
        return AKTUALIS_UGYFEL_MEGSZOLITAS;
    }

    public void setAKTUALIS_UGYFEL_MEGSZOLITAS(String AKTUALIS_UGYFEL_MEGSZOLITAS) {
        this.AKTUALIS_UGYFEL_MEGSZOLITAS = AKTUALIS_UGYFEL_MEGSZOLITAS;
    }

    public String getAKTUALIS_UGYFEL_KERESZTNEV() {
        return AKTUALIS_UGYFEL_KERESZTNEV;
    }

    public void setAKTUALIS_UGYFEL_KERESZTNEV(String AKTUALIS_UGYFEL_KERESZTNEV) {
        this.AKTUALIS_UGYFEL_KERESZTNEV = AKTUALIS_UGYFEL_KERESZTNEV;
    }

    public String getAKTUALIS_UGYFEL_VEZETEKNEV() {
        return AKTUALIS_UGYFEL_VEZETEKNEV;
    }

    public void setAKTUALIS_UGYFEL_VEZETEKNEV(String AKTUALIS_UGYFEL_VEZETEKNEV) {
        this.AKTUALIS_UGYFEL_VEZETEKNEV = AKTUALIS_UGYFEL_VEZETEKNEV;
    }

    public String getAKTUALIS_UGYFEL_EMAIL() {
        return AKTUALIS_UGYFEL_EMAIL;
    }

    public void setAKTUALIS_UGYFEL_EMAIL(String AKTUALIS_UGYFEL_EMAIL) {
        this.AKTUALIS_UGYFEL_EMAIL = AKTUALIS_UGYFEL_EMAIL;
    }

    public String getAKTUALIS_UGYFEL_TELEFON() {
        return AKTUALIS_UGYFEL_TELEFON;
    }

    public void setAKTUALIS_UGYFEL_TELEFON(String AKTUALIS_UGYFEL_TELEFON) {
        this.AKTUALIS_UGYFEL_TELEFON = AKTUALIS_UGYFEL_TELEFON;
    }
}


